services:
  - type: web
    name: worldguessr-tracker
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.12"
    buildCommand: |
      python -m venv .venv
      .venv/bin/pip install --upgrade pip
      .venv/bin/pip install -r requirements.txt
    startCommand: ".venv/bin/gunicorn main:app"
    envVars:
      - key: CHAT_ID
        value: "7664721918"
      - key: TELEGRAM_BOT_TOKEN
        value: "7563042432:AAGl7upiQiU3Gohr6HUPennLkC_P5kba2go"
