services:
  - type: web
    name: worldguessr-tracker       # Nom de ton service sur Render
    env: python
    region: oregon                  # RÃ©gion Oregon (US West)
    plan: free                      # Choisis le plan que tu veux
    pythonVersion: "3.12"           # Version exacte de Python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: CHAT_ID
        value: "7664721918"
      - key: TELEGRAM_BOT_TOKEN
        value: "7563042432:AAGl7upiQiU3Gohr6HUPennLkC_P5kba2go"
